datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://127.0.0.1:3306/test`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:rootroot}
    driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
    dialect: org.hibernate.dialect.MySQL8Dialect

jpa:
  default:
    packages-to-scan:
      - 'com.projectBackEnd.Entities.Medicine'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

micronaut:
  server:
    maxRequestSize: 1MB
    host: localhost
    netty:
      maxHeaderSize: 500KB
      worker:
        threads: 8
      childOptions:
        autoRead: true
