runtime: java
env: flex
beta_settings:
  cloud_sql_instances: even-kite-271719:europe-west2:segmedapp01773=tcp:3306

datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://127.0.0.1:3306/segmajor0105`}
    username: ${JDBC_USER:client}
    password: ${JDBC_PASSWORD:testClientPw}
    driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
    dialect: org.hibernate.dialect.MySQL8Dialect

jpa:
  default:
    packages-to-scan:
      - 'com.projectBackEnd.Entities.Medicine'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

micronaut:
  server:
    maxRequestSize: 1MB
    host: localhost
    netty:
      maxHeaderSize: 500KB
      worker:
        threads: 8
      childOptions:
        autoRead: true
