datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql:///segmajor0105?cloudSqlInstance=even-kite-271719:europe-west2:segmedapp01773&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=client&password=testClientPw`}
    username: ${JDBC_USER:client}
    password: ${JDBC_PASSWORD:testClientPw}
    driverClassName: ${JDBC_DRIVER:com.mysql.jdbc.Driver}
    dialect: org.hibernate.dialect.MySQL8Dialect

jpa:
  default:
    packages-to-scan:
      - 'com.projectBackEnd.Entities.Medicine'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

micronaut:
  server:
    cors: 
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:8081
    maxRequestSize: 100MB
    multipart:
      maxFileSize: 100MB
    host: localhost
    netty:
      maxHeaderSize: 500KB
      worker:
        threads: 8
      childOptions:
        autoRead: true
