swagger: '2.0'
info:
  version: 1.0.0
  title: King's College Hospital - Paediatric Liver Service
  contact:
    url: ''
    email: ''
  description: KCH Paediatric Liver Service website API.
  license:
    url: ''
    name: ''
tags:
- name: sites
  description: Create, retrieve, update and delete sites and their pages
- name: images
  description: Image uploading and management
- name: news
  description: Create, retrieve, update and delete news posts
- name: medicines
  description: Create, retrieve, update and delete medicines
paths:
  /sites:
    get:
      tags:
      - sites
      summary: Get a list of all sites
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/SiteDescription'
    post:
      tags:
      - sites
      summary: Add a new site
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Site object to be added
        required: true
        schema:
          $ref: '#/definitions/SiteDescription'
      responses:
        201:
          description: Created
      security:
      - ApiKeyHeader: []
  /sites/{siteSlug}:
    parameters:
    - name: siteSlug
      in: path
      description: Site slug
      required: true
      type: string
    get:
      tags:
      - sites
      summary: Get a site and all of its pages
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Site'
    put:
      summary: Update an existing site
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Site object to be updated
        required: true
        schema:
          $ref: '#/definitions/SiteDescription'
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
      - sites
    delete:
      summary: Delete an existing site
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
        - sites
  /sites/{siteSlug}/pages:
    parameters:
    - name: siteSlug
      in: path
      description: Site slug
      required: true
      type: string
    post:
      tags:
      - sites
      summary: Add a new page
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Site object to be added
        required: true
        schema:
          $ref: '#/definitions/Page'
      responses:
        201:
          description: Created
      security:
      - ApiKeyHeader: []
  /sites/{siteSlug}/pages/{pageSlug}:
    parameters:
    - name: siteSlug
      in: path
      description: Site slug
      required: true
      type: string
    - name: pageSlug
      in: path
      description: Page slug
      required: true
      type: string
    get:
      tags:
      - sites
      summary: Get a page
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Page'
    put:
      summary: Update an existing page
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Site object to be updated
        required: true
        schema:
          $ref: '#/definitions/Page'
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
      - sites
    delete:
      summary: Delete an existing page
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
      - sites
  /sites/{siteSlug}/page-indices:
    parameters:
    - name: siteSlug
      in: path
      description: Site slug
      required: true
      type: string
    patch:
      tags:
      - sites
      summary: Alter page indices for all pages in a site
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Array of sites and their indices
        required: true
        schema:
          type: array
          items:
            $ref: '#/definitions/PageIndex'
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
  /images:
    post:
      tags:
      - images
      summary: Add a new image
      consumes:
      - multipart/form-data
      produces:
      - application/json
      parameters:
      - in: formData
        name: image
        description: Image content
        required: true
        type: file
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/Image'
      security:
      - ApiKeyHeader: []
  /images/{imageUrl}:
    parameters:
    - name: imageUrl
      in: path
      description: Image URL
      required: true
      type: string
    delete:
      tags:
      - images
      summary: Delete an existing image
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
  /news:
    get:
      tags:
      - news
      summary: Get a list of all news
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/News'
    post:
      tags:
      - news
      summary: Add a new news post
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Site object to be added
        required: true
        schema:
          $ref: '#/definitions/News'
      responses:
        201:
          description: Created
      security:
      - ApiKeyHeader: []
  /news/{newsSlug}:
    parameters:
    - name: newsSlug
      in: path
      description: News slug
      required: true
      type: string
    put:
      summary: Update an existing news post
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: News object to be updated
        required: true
        schema:
          $ref: '#/definitions/News'
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
      - news
    delete:
      summary: Delete an existing news post
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
        - news
  /medicines:
    get:
      tags:
      - medicines
      summary: Get a list of all medicines
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Medicine'
    put:
      summary: Update an existing medicine
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Medicine object to be updated
        required: true
        schema:
          $ref: '#/definitions/Medicine'
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
      - medicines
    post:
      tags:
      - medicines
      summary: Add a new medicine
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Medicine object to be added
        required: true
        schema:
          $ref: '#/definitions/Medicine'
      responses:
        201:
          description: Created
      security:
      - ApiKeyHeader: []
  /medicines/{medicineId}:
    parameters:
    - name: medicineId
      in: path
      description: Medicine ID
      required: true
      type: number
    delete:
      summary: Delete an existing medicine
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
        - medicines
securityDefinitions:
  ApiKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key
definitions:
  SiteDescription:
    type: object
    properties:
      slug:
        type: string
        example: biliary-atresia
      name:
        type: string
        example: Biliary Atresia
      description:
        type: string
        example: A rare disease of the liver and bile ducts that occurs in infants.
      published:
        type: boolean
  Site:
    allOf:
    - $ref: '#/definitions/SiteDescription'
    - type: object
      properties:
        pages:
          type: array
          items:
            $ref: '#/definitions/Page'
  Page:
    allOf:
    - $ref: '#/definitions/PageIndex'
    - type: object
      properties:
        title:
          type: string
          example: Introduction
        content:
          type: string
        published:
          type: boolean
  PageIndex:
    type: object
    properties:
      slug:
        type: string
        example: introduction
      index:
        type: integer
        example: 0
  Image:
    type: object
    properties:
      imageUrl:
        type: string
        example: https://example.com/images/202002281.png
  News:
    type: object
    properties:
      title:
        type: string
        example: Coronavirus Information
      description:
        type: string
        example: Read our official advice regarding COVID-19.
      content:
        type: string
      slug:
        type: string
        example: 20200315-coronavirus-information
      date:
        type: string
        format: date
        example: 2020-03-15
      pinned:
        type: boolean
        example: true
      urgent:
        type: boolean
        example: false
  Medicine:
    type: object
    properties:
      id:
        type: number
      name:
        type: string
        example: Ursodeoxycholic Acid
      type:
        type: string
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /CallumWatkins/KCH-PLS/1.0.0
schemes:
 - https