swagger: '2.0'
info:
  version: 1.0.0
  title: King's College Hospital - Paediatric Liver Service
  contact:
    url: ""
    email: ""
  description: KCH Paediatric Liver Service website API.
  license:
    url: ""
    name: ""
tags:
  - name: sites
    description: Create, retrieve, update and delete sites and their pages
paths:
  /sites:
    get:
      tags:
      - sites
      summary: Get a list of all sites
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SiteDescription"
    post:
      tags:
      - sites
      summary: Add a new site
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Site object to be added
        required: true
        schema:
          $ref: '#/definitions/SiteDescription'
      responses:
        201:
          description: Created
      security:
      - ApiKeyHeader: []
  /sites/{siteSlug}:
    parameters:
    - name: "siteSlug"
      in: "path"
      description: "Slug of site"
      required: true
      type: "string"
    get:
      tags:
      - sites
      summary: Get a site and all of its pages
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Site"
    put:
      summary: Update an existing site
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Site object to be updated
        required: true
        schema:
          $ref: '#/definitions/SiteDescription'
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
        - sites
  /sites/{siteSlug}/pages:
    parameters:
    - name: "siteSlug"
      in: "path"
      description: "Slug of site to add a page to"
      required: true
      type: "string"
    post:
      tags:
      - sites
      summary: Add a new page
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Site object to be added
        required: true
        schema:
          $ref: '#/definitions/Page'
      responses:
        201:
          description: Created
      security:
      - ApiKeyHeader: []
  /sites/{siteSlug}/pages/{pageSlug}:
    parameters:
    - name: "siteSlug"
      in: "path"
      description: "Slug of site that page to update belongs to"
      required: true
      type: "string"
    - name: "pageSlug"
      in: "path"
      description: "Slug of page to update"
      required: true
      type: "string"
    put:
      summary: Update an existing page
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Site object to be updated
        required: true
        schema:
          $ref: '#/definitions/SiteDescription'
      responses:
        204:
          description: No content
      security:
      - ApiKeyHeader: []
      tags:
        - sites
securityDefinitions:
  ApiKeyHeader:
    type: apiKey
    in: header
    name: X-API-Key
definitions:
  SiteDescription:
    type: object
    properties:
      slug:
        type: string
        example: biliary-atresia
      name:
        type: string
        example: Biliary Atresia
      description:
        type: string
        example: A rare disease of the liver and bile ducts that occurs in infants.
      published:
        type: boolean
  Site:
    allOf:
    - $ref: '#/definitions/SiteDescription'
    - type: object
      properties:
        pages:
          type: array
          items:
            $ref: '#/definitions/Page'
  Page:
    type: object
    properties:
      slug:
        type: string
        example: introduction
      index:
        type: integer
        example: 0
      title:
        type: string
        example: Introduction
      content:
        type: string
      published:
        type: boolean
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /CallumWatkins/KCH-PLS/1.0.0
schemes:
 - https